/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedBrandRouteImport } from './routes/_authenticated.brand'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedBrandIndexRouteImport } from './routes/_authenticated.brand.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedBrandTransactionsRouteImport } from './routes/_authenticated.brand.transactions'
import { Route as AuthenticatedBrandDealsRouteImport } from './routes/_authenticated.brand.deals'
import { Route as AuthenticatedBrandCommissionsRouteImport } from './routes/_authenticated.brand.commissions'
import { Route as AuthenticatedBrandApplyRouteImport } from './routes/_authenticated.brand.apply'
import { Route as AuthenticatedAppVerifyRouteImport } from './routes/_authenticated.app.verify'
import { Route as AuthenticatedAppMembershipRouteImport } from './routes/_authenticated.app.membership'
import { Route as AuthenticatedAppDealsRouteImport } from './routes/_authenticated.app.deals'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated.admin.verifications'
import { Route as AuthenticatedAdminGroupsRouteImport } from './routes/_authenticated.admin.groups'
import { Route as AuthenticatedAdminDealsRouteImport } from './routes/_authenticated.admin.deals'
import { Route as AuthenticatedAdminBrandsRouteImport } from './routes/_authenticated.admin.brands'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated.admin.analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBrandRoute = AuthenticatedBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrandIndexRoute = AuthenticatedBrandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedBrandRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedBrandTransactionsRoute =
  AuthenticatedBrandTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedBrandRoute,
  } as any)
const AuthenticatedBrandDealsRoute = AuthenticatedBrandDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedBrandRoute,
} as any)
const AuthenticatedBrandCommissionsRoute =
  AuthenticatedBrandCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedBrandRoute,
  } as any)
const AuthenticatedBrandApplyRoute = AuthenticatedBrandApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AuthenticatedBrandRoute,
} as any)
const AuthenticatedAppVerifyRoute = AuthenticatedAppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMembershipRoute =
  AuthenticatedAppMembershipRouteImport.update({
    id: '/membership',
    path: '/membership',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDealsRoute = AuthenticatedAppDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGroupsRoute =
  AuthenticatedAdminGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDealsRoute = AuthenticatedAdminDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBrandsRoute =
  AuthenticatedAdminBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/brand': typeof AuthenticatedBrandRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/deals': typeof AuthenticatedAdminDealsRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/app/deals': typeof AuthenticatedAppDealsRoute
  '/app/membership': typeof AuthenticatedAppMembershipRoute
  '/app/verify': typeof AuthenticatedAppVerifyRoute
  '/brand/apply': typeof AuthenticatedBrandApplyRoute
  '/brand/commissions': typeof AuthenticatedBrandCommissionsRoute
  '/brand/deals': typeof AuthenticatedBrandDealsRoute
  '/brand/transactions': typeof AuthenticatedBrandTransactionsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/brand/': typeof AuthenticatedBrandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/deals': typeof AuthenticatedAdminDealsRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/app/deals': typeof AuthenticatedAppDealsRoute
  '/app/membership': typeof AuthenticatedAppMembershipRoute
  '/app/verify': typeof AuthenticatedAppVerifyRoute
  '/brand/apply': typeof AuthenticatedBrandApplyRoute
  '/brand/commissions': typeof AuthenticatedBrandCommissionsRoute
  '/brand/deals': typeof AuthenticatedBrandDealsRoute
  '/brand/transactions': typeof AuthenticatedBrandTransactionsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/brand': typeof AuthenticatedBrandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/brand': typeof AuthenticatedBrandRouteWithChildren
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/_authenticated/admin/deals': typeof AuthenticatedAdminDealsRoute
  '/_authenticated/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/app/deals': typeof AuthenticatedAppDealsRoute
  '/_authenticated/app/membership': typeof AuthenticatedAppMembershipRoute
  '/_authenticated/app/verify': typeof AuthenticatedAppVerifyRoute
  '/_authenticated/brand/apply': typeof AuthenticatedBrandApplyRoute
  '/_authenticated/brand/commissions': typeof AuthenticatedBrandCommissionsRoute
  '/_authenticated/brand/deals': typeof AuthenticatedBrandDealsRoute
  '/_authenticated/brand/transactions': typeof AuthenticatedBrandTransactionsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/brand/': typeof AuthenticatedBrandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/brand'
    | '/admin/analytics'
    | '/admin/brands'
    | '/admin/deals'
    | '/admin/groups'
    | '/admin/verifications'
    | '/app/deals'
    | '/app/membership'
    | '/app/verify'
    | '/brand/apply'
    | '/brand/commissions'
    | '/brand/deals'
    | '/brand/transactions'
    | '/admin/'
    | '/app/'
    | '/brand/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/analytics'
    | '/admin/brands'
    | '/admin/deals'
    | '/admin/groups'
    | '/admin/verifications'
    | '/app/deals'
    | '/app/membership'
    | '/app/verify'
    | '/brand/apply'
    | '/brand/commissions'
    | '/brand/deals'
    | '/brand/transactions'
    | '/admin'
    | '/app'
    | '/brand'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/brand'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/brands'
    | '/_authenticated/admin/deals'
    | '/_authenticated/admin/groups'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/app/deals'
    | '/_authenticated/app/membership'
    | '/_authenticated/app/verify'
    | '/_authenticated/brand/apply'
    | '/_authenticated/brand/commissions'
    | '/_authenticated/brand/deals'
    | '/_authenticated/brand/transactions'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/brand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/brand': {
      id: '/_authenticated/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof AuthenticatedBrandRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/brand/': {
      id: '/_authenticated/brand/'
      path: '/'
      fullPath: '/brand/'
      preLoaderRoute: typeof AuthenticatedBrandIndexRouteImport
      parentRoute: typeof AuthenticatedBrandRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/brand/transactions': {
      id: '/_authenticated/brand/transactions'
      path: '/transactions'
      fullPath: '/brand/transactions'
      preLoaderRoute: typeof AuthenticatedBrandTransactionsRouteImport
      parentRoute: typeof AuthenticatedBrandRoute
    }
    '/_authenticated/brand/deals': {
      id: '/_authenticated/brand/deals'
      path: '/deals'
      fullPath: '/brand/deals'
      preLoaderRoute: typeof AuthenticatedBrandDealsRouteImport
      parentRoute: typeof AuthenticatedBrandRoute
    }
    '/_authenticated/brand/commissions': {
      id: '/_authenticated/brand/commissions'
      path: '/commissions'
      fullPath: '/brand/commissions'
      preLoaderRoute: typeof AuthenticatedBrandCommissionsRouteImport
      parentRoute: typeof AuthenticatedBrandRoute
    }
    '/_authenticated/brand/apply': {
      id: '/_authenticated/brand/apply'
      path: '/apply'
      fullPath: '/brand/apply'
      preLoaderRoute: typeof AuthenticatedBrandApplyRouteImport
      parentRoute: typeof AuthenticatedBrandRoute
    }
    '/_authenticated/app/verify': {
      id: '/_authenticated/app/verify'
      path: '/verify'
      fullPath: '/app/verify'
      preLoaderRoute: typeof AuthenticatedAppVerifyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/membership': {
      id: '/_authenticated/app/membership'
      path: '/membership'
      fullPath: '/app/membership'
      preLoaderRoute: typeof AuthenticatedAppMembershipRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/deals': {
      id: '/_authenticated/app/deals'
      path: '/deals'
      fullPath: '/app/deals'
      preLoaderRoute: typeof AuthenticatedAppDealsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/groups': {
      id: '/_authenticated/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthenticatedAdminGroupsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/deals': {
      id: '/_authenticated/admin/deals'
      path: '/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AuthenticatedAdminDealsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/brands': {
      id: '/_authenticated/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AuthenticatedAdminBrandsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminBrandsRoute: typeof AuthenticatedAdminBrandsRoute
  AuthenticatedAdminDealsRoute: typeof AuthenticatedAdminDealsRoute
  AuthenticatedAdminGroupsRoute: typeof AuthenticatedAdminGroupsRoute
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminBrandsRoute: AuthenticatedAdminBrandsRoute,
  AuthenticatedAdminDealsRoute: AuthenticatedAdminDealsRoute,
  AuthenticatedAdminGroupsRoute: AuthenticatedAdminGroupsRoute,
  AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppDealsRoute: typeof AuthenticatedAppDealsRoute
  AuthenticatedAppMembershipRoute: typeof AuthenticatedAppMembershipRoute
  AuthenticatedAppVerifyRoute: typeof AuthenticatedAppVerifyRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppDealsRoute: AuthenticatedAppDealsRoute,
  AuthenticatedAppMembershipRoute: AuthenticatedAppMembershipRoute,
  AuthenticatedAppVerifyRoute: AuthenticatedAppVerifyRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedBrandRouteChildren {
  AuthenticatedBrandApplyRoute: typeof AuthenticatedBrandApplyRoute
  AuthenticatedBrandCommissionsRoute: typeof AuthenticatedBrandCommissionsRoute
  AuthenticatedBrandDealsRoute: typeof AuthenticatedBrandDealsRoute
  AuthenticatedBrandTransactionsRoute: typeof AuthenticatedBrandTransactionsRoute
  AuthenticatedBrandIndexRoute: typeof AuthenticatedBrandIndexRoute
}

const AuthenticatedBrandRouteChildren: AuthenticatedBrandRouteChildren = {
  AuthenticatedBrandApplyRoute: AuthenticatedBrandApplyRoute,
  AuthenticatedBrandCommissionsRoute: AuthenticatedBrandCommissionsRoute,
  AuthenticatedBrandDealsRoute: AuthenticatedBrandDealsRoute,
  AuthenticatedBrandTransactionsRoute: AuthenticatedBrandTransactionsRoute,
  AuthenticatedBrandIndexRoute: AuthenticatedBrandIndexRoute,
}

const AuthenticatedBrandRouteWithChildren =
  AuthenticatedBrandRoute._addFileChildren(AuthenticatedBrandRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedBrandRoute: typeof AuthenticatedBrandRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedBrandRoute: AuthenticatedBrandRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
